# Generated by Django 4.1.1 on 2022-10-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridal_Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Product name')),
                ('Description', models.CharField(max_length=300, verbose_name='Description')),
                ('Price', models.FloatField(default=1.0, verbose_name=' price')),
                ('product_image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Dowry_Wrapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Product name')),
                ('Description', models.CharField(max_length=300, verbose_name='Description')),
                ('Price', models.FloatField(default=1.0, verbose_name=' price')),
                ('product_image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Souvenirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Product name')),
                ('Description', models.CharField(max_length=300, verbose_name='Description')),
                ('Price', models.FloatField(default=1.0, verbose_name=' price')),
                ('product_image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Bakery',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Boquet',
        ),
    ]
